#render.yaml for automated deployment
cat > render.yaml << 'EOF'
services:
  - type: web
    name: healthcare-chatbot-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: healthcare-db
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        fromDatabase:
          name: mongodb-atlas
          property: connectionString
EOF