// app/services/translator.js
import { useState, useEffect } from 'react';

export const RSA_LANGUAGES = [
  'en', 'af', 'zu', 'xh', 'nso', 'st', 'tn', 'ts', 'ss', 've', 'nr'
];

// Pre-translated content for all SA languages
export const preTranslatedContent = {
  en: {
    welcome: "👋 Hello! I'm VitalAi, your medical assistant. I can help you with:\n\n• 🤒 Symptom checking and triage\n• 📅 Appointment booking\n• ❓ General hospital information\n• 🏥 Department referrals\n\nHow can I assist you today? Please remember I'm an AI assistant and not a substitute for professional medical advice.",
    placeholder: "Describe your symptoms or ask a question...",
    typing: "VitalAi is analyzing your symptoms...",
    quickActions: "Quick Actions",
    symptomCheck: "Symptom Check",
    bookAppointment: "Book Appointment",
    emergency: "Emergency",
    loginRequired: "Login Required",
    loginMessage: "Please login to access this feature",
    loginButton: "Login",
    logout: "Logout",
    cancel: "Cancel",
    confirm: "Confirm",
    send: "Send",
    next: "Next", 
    previous: "Previous",
    headerTitle: "VitalAi",
    headerSubtitle: "Medical Assistant",
    language: "Language",
    appointments: "Appointments",
    chatHistory: "Chat History",
    profile: "Profile",
    login: "Login",
    chat: "Chat",
    you: "You",
    recommended: "Recommended",
    medicalEmergency: "🚨 MEDICAL EMERGENCY",
    emergencyInstructions: "This sounds serious! Please:\n\n• Call 10111 for emergency services\n• Go to the nearest hospital immediately\n• Do not delay seeking professional help",
    callEmergency: "Call 10111",
    symptomChecker: "Symptom Checker",
    mainSymptom: "What is your main symptom today?",
    symptomDuration: "How long have you had these symptoms?",
    symptomSeverity: "How severe is your discomfort?",
    lessThan24: "Less than 24 hours",
    oneToThreeDays: "1-3 days",
    moreThan3Days: "More than 3 days",
    mild: "Mild - can do normal activities",
    moderate: "Moderate - interferes with activities",
    severe: "Severe - cannot do normal activities",
    bookAppointmentTitle: "Book Appointment",
    yourInformation: "Your Information",
    fullName: "Full Name",
    age: "Age",
    contactNumber: "Contact Number",
    appointmentDetails: "Appointment Details",
    selectDepartment: "Select Department:",
    loadingLanguage: "Loading language...",
    appointmentBooked: "✅ Appointment Booked Successfully!",
    appointmentDetailsText: "📋 Details",
    patient: "Patient",
    department: "Department",
    date: "Date",
    time: "Time",
    arrivalNotice: "You will receive a confirmation SMS. Please arrive 15 minutes early."
  },
  af: {
    welcome: "👋 Hallo! Ek is VitalAi, jou mediese assistent. Ek kan help met:\n\n• 🤒 Simptoom nagaan en triage\n• 📅 Afspraak bespreking\n• ❓ Algemene hospitaal inligting\n• 🏥 Departement verwysings\n\nHoe kan ek jou vandag help? Onthou asseblief ek is 'n AI assistent en nie 'n plaasvervanger vir professionele mediese advies nie.",
    placeholder: "Beskryf jou simptome of vra 'n vraag...",
    typing: "VitalAi ontleed jou simptome...",
    quickActions: "Vinnige Aksies",
    symptomCheck: "Simptoom Tjek",
    bookAppointment: "Bespreek Afspraak",
    emergency: "Noodgeval",
    loginRequired: "Aanmelding Vereis",
    loginMessage: "Meld asseblief aan om hierdie funksie te gebruik",
    loginButton: "Teken Aan",
    logout: "Teken Uit",
    cancel: "Kanselleer",
    confirm: "Bevestig",
    send: "Stuur",
    next: "Volgende",
    previous: "Vorige",
    headerTitle: "VitalAi",
    headerSubtitle: "Mediese Assistent",
    language: "Taal",
    appointments: "Afsprake",
    chatHistory: "Kletsgeskiedenis",
    profile: "Profiel",
    login: "Teken Aan",
    chat: "Klets",
    you: "Jy",
    recommended: "Aanbeveel",
    medicalEmergency: "🚨 MEDIESE NOODGEWAL",
    emergencyInstructions: "Dit klink ernstig! Asseblief:\n\n• Skakel 10111 vir nooddienste\n• Gaan na die naaste hospitaal onmiddellik\n• Moet nie uitstel om professionele hulp te soek nie",
    callEmergency: "Skakel 10111",
    symptomChecker: "Simptoom Kontroleerder",
    mainSymptom: "Wat is jou hoofsimptoom vandag?",
    symptomDuration: "Hoe lank het jy al hierdie simptome?",
    symptomSeverity: "Hoe erg is jou ongemak?",
    lessThan24: "Minder as 24 uur",
    oneToThreeDays: "1-3 dae",
    moreThan3Days: "Meer as 3 dae",
    mild: "Lig - kan normale aktiwiteite doen",
    moderate: "Matig - belemmer aktiwiteite",
    severe: "Ernstig - kan nie normale aktiwiteite doen nie",
    bookAppointmentTitle: "Bespreek Afspraak",
    yourInformation: "Jou Inligting",
    fullName: "Volle Naam",
    age: "Ouderdom",
    contactNumber: "Kontaknommer",
    appointmentDetails: "Afspraak Besonderhede",
    selectDepartment: "Kies Departement:",
    loadingLanguage: "Laai taal...",
    appointmentBooked: "✅ Afspraak Suksesvol Bespreek!",
    appointmentDetailsText: "📋 Besonderhede",
    patient: "Pasient",
    department: "Departement",
    date: "Datum",
    time: "Tyd",
    arrivalNotice: "Jy sal 'n bevestigings SMS ontvang. Kom asseblief 15 minute vroeg aan."
  },
  zu: {
    welcome: "👋 Sawubona! Ngingu-VitalAi, umsizi wakho wezempilo. Ngingakusiza nge:\n\n• 🤒 Ukuhlola izimpawu kanye nokuhlela\n• 📅 Ukubhuka izikhathi zokuhlangana\n• ❓ Ulwazi lwesibhedlela jikelele\n• 🏥 Izinkomba zomnyango\n\nNgingakusiza kanjani namuhla? Ngicela ukhumbule ukuthi ngingumsizi we-AI hhayi indlela yokushintsha iseluleko somuntu osemthethweni sezempilo.",
    placeholder: "Chaza izimpawu zakho noma buza umbuzo...",
    typing: "U-VitalAi uhlaziya izimpawu zakho...",
    quickActions: "Izenzo Ezisheshayo",
    symptomCheck: "Hlola Izimpawu",
    bookAppointment: "Bhuka Isikhathi",
    emergency: "Ukuphazamiseka",
    loginRequired: "Ukungena Kuyadingeka",
    loginMessage: "Sicela ungene ukufinyelela lesi sici",
    loginButton: "Ngena",
    logout: "Phuma",
    cancel: "Khansela",
    confirm: "Qinisekisa",
    send: "Thumela",
    next: "Olandelayo",
    previous: "Edlule",
    headerTitle: "VitalAi",
    headerSubtitle: "UmSizi WezeMpilo",
    language: "Ulimi",
    appointments: "Izikhathi",
    chatHistory: "Umlando Wengxoxo",
    profile: "Iphrofayili",
    login: "Ngena",
    chat: "Ingxoxo",
    you: "Wena",
    recommended: "Kunconywe",
    medicalEmergency: "🚨 INGXAKI EPHUTHUMAYO YEZEMPILO",
    emergencyInstructions: "Lokhu kuzwakala kubalulekile! Sicela:\n\n• Shayela u-10111 wamasevisi aphuthumayo\n• Iya esibhedlela esiseduzane ngokushesha\n• Ungabambi ithuba lokufuna usizo lobungcweti",
    callEmergency: "Shayela u-10111",
    symptomChecker: "Isihloli Sezimpawu",
    mainSymptom: "Iyiphi impawu yakho eyinhloko namuhla?",
    symptomDuration: "Ubesenazo isikhathi esingakanani lezi zimpawu?",
    symptomSeverity: "Zimbi kangakanani izinkinga zakho?",
    lessThan24: "Ngaphansi kwamahora angu-24",
    oneToThreeDays: "Izinsuku ezi-1-3",
    moreThan3Days: "Izinsuku ezingaphezu kwezi-3",
    mild: "Kuncane - ngenza imisebenzi evamile",
    moderate: "Okuphakathi nendawo - kuphazamisa imisebenzi",
    severe: "Kubi kakhulu - angikwazi ukwenza imisebenzi evamile",
    bookAppointmentTitle: "Bhuka Isikhathi",
    yourInformation: "Ulwazi Lwakho",
    fullName: "Igama Eliphelele",
    age: "Iminyaka",
    contactNumber: "Inombolo Yocingo",
    appointmentDetails: "Imininingwane Yesikhathi",
    selectDepartment: "Khetha uMnyango:",
    loadingLanguage: "Ilayisha ulimi...",
    appointmentBooked: "✅ Isikhathi Sibhukiwe Ngempumelelo!",
    appointmentDetailsText: "📋 Imininingwane",
    patient: "Isiguli",
    department: "UMnyango",
    date: "Usuku",
    time: "Isikhathi",
    arrivalNotice: "Uzothola i-SMS yokuqinisekisa. Sicela ufike imizuzu engu-15 kusenesikhathi."
  },
  xh: {
    welcome: "👋 Molo! Ndingu-VitalAi, umncedi wakho wezempilo. Ndinokuncedisa nge:\n\n• 🤒 Uvavanyo lweempawu kunye nokulandelelana\n• 📅 Ukucwangcisa ixesha lomhlanganyelo\n• ❓ Ulwazi lweshospitali jikelele\n• 🏥 Iindlela zokudlulisela kwicandelo\n\nNdingakunceda njani namhlanje? Nceda khumbula ukuba ndingumncedi we-AI hayinto etshintsha icebiso legqirha elisemthethweni.",
    placeholder: "Chaza iimpawu zakho okanye buza umbuzo...",
    typing: "U-VitalAi uhlalutya iimpawu zakho...",
    quickActions: "Izenzo Ezikhawulezileyo",
    symptomCheck: "Khangela Iimpawu",
    bookAppointment: "Bhuka Ixesha",
    emergency: "Ingxaki ephuthumayo",
    loginRequired: "Ukungena Kuyafuneka",
    loginMessage: "Nceda ungene ukufikelela kwesi sifundo",
    loginButton: "Ngena",
    logout: "Phuma",
    cancel: "Rhoxisa",
    confirm: "Qinisekisa",
    send: "Thumela",
    next: "Okulandelayo",
    previous: "Edlulileyo",
    headerTitle: "VitalAi",
    headerSubtitle: "UmNcedi WezeMpilo",
    language: "Ulimi",
    appointments: "Ixesha",
    chatHistory: "Imbali Yengxoxo",
    profile: "Iprofayili",
    login: "Ngena",
    chat: "Ingxoxo",
    you: "Wena",
    recommended: "Icelwe",
    medicalEmergency: "🚨 INGXAKI EPHUTHUMAYO YEZEMPILO",
    emergencyInstructions: "Oku kubonakala kubalulekile! Nceda:\n\n• Biza u-10111 ngeenkonzo eziphuthumayo\n• Yiya kwihospitali ekufutshane ngokukhawuleza\n• Musa ukulibaziseka ukufuna uncedo lobuchule",
    callEmergency: "Biza u-10111",
    symptomChecker: "Umhloli Weempawu",
    mainSymptom: "Yeyiphi impawu yakho ephambili namhlanje?",
    symptomDuration: "Ixesha elingakanani unalo ezi mpawu?",
    symptomSeverity: "Ibi mbi kangakanani iingxaki zakho?",
    lessThan24: "Ngaphantsi kweeawusi ezingama-24",
    oneToThreeDays: "Iintsuku ezi-1-3",
    moreThan3Days: "Iintsuku ezingaphezu kwezi-3",
    mild: "Incinci - ngenza imisebenzi eqhelekileyo",
    moderate: "Umphakathi - iphazamisa imisebenzi",
    severe: "Ibi mbi - andikwazi ukwenza imisebenzi eqhelekileyo",
    bookAppointmentTitle: "Bhuka Ixesha",
    yourInformation: "Inkcazelo Yakho",
    fullName: "Igama Elipheleleyo",
    age: "Iminyaka",
    contactNumber: "Inombolo Yonxibelelwano",
    appointmentDetails: "Iinkcukacha Zexesha",
    selectDepartment: "Khetha iCandelo:",
    loadingLanguage: "Ilayisha ulwimi...",
    appointmentBooked: "✅ Ubhukishe uMhlangano ngempumelelo!",
    appointmentDetailsText: "📋 Iinkcukacha",
    patient: "Isigulane",
    department: "Icandelo",
    date: "Umhla",
    time: "Ixesha",
    arrivalNotice: "Uza kufumana iSMS yokuqinisekisa. Nceda ufike imizuzu eyi-15 ngaphambi."
  },
  nso: {
    welcome: "👋 Dumela! Ke VitalAi, mothusi wa gago wa tša maphelo. Nka go thusa ka:\n\n• 🤒 Go hlahloba maswabi le go hlopha\n• 📅 Go beakanya dipeakanyo\n• ❓ Tshedimošo ya setlabela ka kakaretšo\n• 🏥 Ditumelelano tša kgoro\n\nNka go thusa bjang lehono? Hle gopola gore ke mothusi wa AI ebile e se moemeli wa keletšo ya setsebi sa tša maphelo.",
    placeholder: "Hlalosa maswabi a gago goba botšiš potšišo...",
    typing: "VitalAi e sekaseka maswabi a gago...",
    quickActions: "Ditiro Tša Ka Pelo",
    symptomCheck: "Hlola Maswabi",
    bookAppointment: "Beakanya Peakanyo",
    emergency: "Tlhokego ya Tšhoganetšo",
    loginRequired: "Go Nyakega Go Kena",
    loginMessage: "Hle kena go šomiša tšhomišo ye",
    loginButton: "Kena",
    logout: "Tšwa",
    cancel: "Khansela",
    confirm: "Tiišetša",
    send: "Romela",
    next: "Go Latela",
    previous: "Go Feta",
    headerTitle: "VitalAi",
    headerSubtitle: "Motlhokomedi wa Tša Maphelo",
    language: "Polelo",
    appointments: "Dipeakanyo",
    chatHistory: "Histori ya Poledišano",
    profile: "Profile",
    login: "Kena",
    chat: "Poledišano",
    you: "Wena",
    recommended: "E šišintšwego",
    medicalEmergency: "🚨 TLHOKEGO YA TŠHOGANETŠO YA MAPHELO",
    emergencyInstructions: "Se se kwešišega bohlokwa! Hle:\n\n• Letela 10111 bakeng sa ditshebeletšo tša tšhoganetšo\n• Eya setlabeleng se se ka kgauswi ka pela\n• O se ke wa latelela go nyaka thuso ya setsebi",
    callEmergency: "Letela 10111",
    symptomChecker: "Mohloli wa Maswabi",
    mainSymptom: "Ke maswabi afe a mantši lehono?",
    symptomDuration: "O na le nako efe e maswabi a?",
    symptomSeverity: "Maswabi a a boima bjang?",
    lessThan24: "Ka fase ga diiri tše 24",
    oneToThreeDays: "Matšatši a 1-3",
    moreThan3Days: "Matšatši a go feta 3",
    mild: "Boleta - nka dira mediro ya mehla",
    moderate: "Magareng - e sitisa mediro",
    severe: "Boima - ga ke kgone go dira mediro ya mehla",
    bookAppointmentTitle: "Beakanya Peakanyo",
    yourInformation: "Tshedimošo Ya Gago",
    fullName: "Leina La Botlalo",
    age: "Menkgahla",
    contactNumber: "Nomoro Ya Kgokagano",
    appointmentDetails: "Dintlha Tša Peakanyo",
    selectDepartment: "Kgetha Kgoro:",
    loadingLanguage: "Laoda polelo...",
    appointmentBooked: "✅ Peakanyo e Beakantšwe Ka Katlego!",
    appointmentDetailsText: "📋 Dintlha",
    patient: "Mokudi",
    department: "Kgoro",
    date: "Letšatši",
    time: "Nako",
    arrivalNotice: "O tla amogela SMS ya tiišetšo. Hle tla metsotso e 15 pele."
  },
  st: {
    welcome: "👋 Lumela! Ke VitalAi, motsoalle oa hau oa bongaka. Ke ka u thusa ka:\n\n• 🤒 Ho hlahloba matšoao le ho arola\n• 📅 Ho beha kopo ea nako ea puisano\n• ❓ Lintlha tsa sepetlele ka kakaretso\n• 🏥 Lipuisano tsa lekala\n\nKe ka u thusa joang kajeno? Ke kopa u hopote hore ke motsoalle oa AI eseng moemeli oa keletso ea setsebi sa bongaka.",
    placeholder: "Hlalosa matšoao a hau kapa botsa potso...",
    typing: "VitalAi e hlahloba matšoao a hau...",
    quickActions: "Litšebetso Tsa Potlako",
    symptomCheck: "Hlahloba Matšoao",
    bookAppointment: "Beha Kopo ea Nako",
    emergency: "Tlhokahalo e Potlakileng",
    loginRequired: "Ho Kenya Tsebo Ho Hlokeha",
    loginMessage: "Ka kopo kena ho fumana tšobotsi ena",
    loginButton: "Kena",
    logout: "Tsoa",
    cancel: "Hlakola",
    confirm: "Netefatsa",
    send: "Romela",
    next: "E 'Moho",
    previous: "E Fetileng",
    headerTitle: "VitalAi",
    headerSubtitle: "Motsoalle oa Bongaka",
    language: "Puo",
    appointments: "Likopo tsa Nako",
    chatHistory: "Histori ea Puisano",
    profile: "Profile",
    login: "Kena",
    chat: "Puisano",
    you: "Uena",
    recommended: "E Khothalelitsoe",
    medicalEmergency: "🚨 TLHOKAHALO E POTLAKILENG EA BONGAKA",
    emergencyInstructions: "Sena se utloahala se le botebo! Ka kopo:\n\n• Bitsa 10111 bakeng sa lits'ebeletso tsa tlhokahalo\n• Ea sepetleling se haufi hang-hang\n• Se liehe ho batla thuso ea setsebi",
    callEmergency: "Bitsa 10111",
    symptomChecker: "Mohloli oa Matšoao",
    mainSymptom: "Ke matšoao afe a mantlha kajeno?",
    symptomDuration: "O 'nil'e le nako e kae e matšoao a?",
    symptomSeverity: "Matšoao a boima bakang?",
    lessThan24: "Ka tlase lihora tse 24",
    oneToThreeDays: "Matsatsi a 1-3",
    moreThan3Days: "Matsatsi a fetang 3",
    mild: "Bonolo - ka etsa mesebetsi e tloaelehileng",
    moderate: "Bohareng - e sitisa mesebetsi",
    severe: "Boima - ke ke ke etse mesebetsi e tloaelehileng",
    bookAppointmentTitle: "Beha Kopo ea Nako",
    yourInformation: "Lintlha Tsa Hau",
    fullName: "Leina ka Botlalo",
    age: "Lilemo",
    contactNumber: "Nomoro ea Kopano",
    appointmentDetails: "Lintlha Tsa Kopo ea Nako",
    selectDepartment: "Khetha Lekala:",
    loadingLanguage: "Kenya puo...",
    appointmentBooked: "✅ Kopo ea Nako e Beiloe Ka Katleho!",
    appointmentDetailsText: "📋 Lintlha",
    patient: "Mokudi",
    department: "Lekala",
    date: "Letsatsi",
    time: "Nako",
    arrivalNotice: "U tla fumana SMS ea netefatso. Ka kopo fihla metsotso e 15 pele."
  },
  tn: {
    welcome: "👋 Dumela! Ke VitalAi, motlhokomedi wa gago wa tsa kalafi. Ke ka go thusa ka:\n\n• 🤒 Go sekaseka matshwao le go arola\n• 📅 Go beakanya ditlhopha\n• ❓ Tshedimosetso ya bookelo ka kakaretso\n• 🏥 Dikgolagano tsa lefapha\n\nKe ka go thusa jang gompieno? Ke kopa gopola gore ke motlhokomedi wa AI eseng moemedi wa dikeletso tsa setsebi sa tsa kalafi.",
    placeholder: "Hlalosa matshwao a gago kaa botsa potso...",
    typing: "VitalAi e sekaseka matshwao a gago...",
    quickActions: "Ditiragatso Tsa Bonako",
    symptomCheck: "Sekaseka Matshwao",
    bookAppointment: "Beakanya Tlhopha",
    emergency: "Tlhokego ya Tshoganetso",
    loginRequired: "Go Tsenya Login Go A Tlhoka",
    loginMessage: "Ka kopo tsena go fitlhelela tiro ena",
    loginButton: "Tsenya",
    logout: "Tswa",
    cancel: "Khansela",
    confirm: "Tlhomamisa",
    send: "Romela",
    next: "Go Latelang",
    previous: "Go Fetileng",
    headerTitle: "VitalAi",
    headerSubtitle: "Motlhokomedi wa Tsa Kalafi",
    language: "Puo",
    appointments: "Ditlhopha",
    chatHistory: "Ditiragalo tsa Poledisano",
    profile: "Porofaele",
    login: "Tsenya",
    chat: "Poledisano",
    you: "Wena",
    recommended: "E Dumeletswe",
    medicalEmergency: "🚨 TLHOKEGO YA TSHOGANETSO YA KALAFI",
    emergencyInstructions: "Se se utlwala botlhokwa! Ka kopo:\n\n• Oelele 10111 bakeng sa ditirelo tsa tshoganetso\n• Eya bookelong jo bo gaufi ka bonako\n• O se ka wa latelela go batla thuso ya setsebi",
    callEmergency: "Oelele 10111",
    symptomChecker: "Mosekasedi wa Matshwao",
    mainSymptom: "Ke matshwao afe a magolo gompieno?",
    symptomDuration: "O na le nako efe e matshwao a?",
    symptomSeverity: "Matshwao a a boima jang?",
    lessThan24: "Ka tlase ga diura di le 24",
    oneToThreeDays: "Matsatsi a 1-3",
    moreThan3Days: "Matsatsi a a fetang 3",
    mild: "Bonolo - nka dira ditiro tsa mehla",
    moderate: "Bogare - e sitisa ditiro",
    severe: "Boima - ga ke kgone go dira ditiro tsa mehla",
    bookAppointmentTitle: "Beakanya Tlhopha",
    yourInformation: "Tshedimosetso Ya Gago",
    fullName: "Leina Le Feletseng",
    age: "Dingwaga",
    contactNumber: "Nomoro ya Kgolagano",
    appointmentDetails: "Dintlha Tsa Tlhopha",
    selectDepartment: "Kgetha Lefapha:",
    loadingLanguage: "Laoda puo...",
    appointmentBooked: "✅ Tlhopha e Beakantswe Ka Katlego!",
    appointmentDetailsText: "📋 Dintlha",
    patient: "Mokudi",
    department: "Lefapha",
    date: "Letsatsi",
    time: "Nako",
    arrivalNotice: "O tla amogela SMS ya tshepidiso. Ka kopo tla metsotso e 15 pele."
  },
  ts: {
    welcome: "👋 Avuxeni! Ndi VitalAi, muperisti wa wena wa vutshunguri. Ndi nga ku pfuna hi:\n\n• 🤒 Ku lavisisa swilo leswi nga rivali na ku hlanganisa\n• 📅 Ku endla xibalo xa nkarhi\n• ❓ Vuxokoxoko bya vandla ra vutshunguri hi xiyimo xa ntlawa\n• 🏥 Swifambiselo swa xiyimo\n\nNdi nga ku pfuna njhani namuntlha? Ndzi kombela u tsundzuka leswaku ndi muperisti wa AI naswona a ndzi riki muperisti wa mpfumelelo wa vutshunguri bya xirho.",
    placeholder: "Hlamusela swilo leswi nga rivali kumbe vutisa xivutiso...",
    typing: "VitalAi yi lava swilo leswi nga rivali...",
    quickActions: "Swiyimo Swa Nkangu",
    symptomCheck: "Lavisisa Swilo Leswi Nga Rivali",
    bookAppointment: "Endla Xibalo",
    emergency: "Nkarhinyana wa Xipete",
    loginRequired: "Ku Ngetela Ku Lava",
    loginMessage: "Ndzi kombela u ngetela ku kuma xiyimo lexi",
    loginButton: "Ngetela",
    logout: "Humela",
    cancel: "Hansi",
    confirm: "Tiyisisa",
    send: "Rhumelela",
    next: "Landzelaka",
    previous: "Sungula",
    headerTitle: "VitalAi",
    headerSubtitle: "Muperisti wa Vutshunguri",
    language: "Ririmi",
    appointments: "Swibalo",
    chatHistory: "Matimu ya Nkumba",
    profile: "Purofayili",
    login: "Ngetela",
    chat: "Nkumba",
    you: "Wena",
    recommended: "Xi Tiseletiwe",
    medicalEmergency: "🚨 NKARHINYANA WA XIPETE WA VUTSHUNGURI",
    emergencyInstructions: "Leswi swi twisisa swa vutomi! Ndzi kombela:\n\n• Rhayela 10111 wa switirhisiwa swa nkarhinyana\n• Yaya evandleni ra vutshunguri lerin'wana ni rin'wana hi ku hatlisa\n• U nga rivali ku lava pfuno ra proferixinala",
    callEmergency: "Rhayela 10111",
    symptomChecker: "Mulavisisi wa Swilo Leswi Nga Rivali",
    mainSymptom: "Yini xivangelo xa wena xa ndzhaku namuntlha?",
    symptomDuration: "Xana u ri ni nkarhi wihi e swivangelo leswi?",
    symptomSeverity: "Xana swivangelo swi tsandzeka kwihi?",
    lessThan24: "Ehansi ka awara ya 24",
    oneToThreeDays: "Masiku ya 1-3",
    moreThan3Days: "Masiku yo hlula ya 3",
    mild: "Ntwanano - nga endla swirho swa ntolovelo",
    moderate: "Xivangelo - swi siverile swirho",
    severe: "Ku tsandzeka - a ndzi koti ku endla swirho swa ntolovelo",
    bookAppointmentTitle: "Endla Xibalo",
    yourInformation: "Vuxokoxoko Bya Wena",
    fullName: "Vito Hinkwaro",
    age: "Malembe",
    contactNumber: "Nomoro ya Ku Hlangana",
    appointmentDetails: "Swivangelo Swa Xibalo",
    selectDepartment: "Hlawula Xiyimo:",
    loadingLanguage: "Layicha ririmi...",
    appointmentBooked: "✅ Xibalo xi Endleriwe Hi Ku Humesa!",
    appointmentDetailsText: "📋 Swivangelo",
    patient: "Muvabyi",
    department: "Xiyimo",
    date: "Siku",
    time: "Nkarhi",
    arrivalNotice: "U ta kuma SMS ya ku tiyisisa. Ndzi kombela u fika iminithi ya 15 leswaku."
  },
  ss: {
    welcome: "👋 Sawubona! Ngingu-VitalAi, umsizi wakho wezempilo. Ngingakusita nge:\n\n• 🤒 Ukuhlola izimpawu kanye nokuhlela\n• 📅 Ukubhuka izikhathi zokuhlangana\n• ❓ Ulwazi lwesibhedlela jikelele\n• 🏥 Izinkomba zomnyango\n\nNgingakusita njani namuhla? Ngicela ukhumbule ukuthi ngingumsizi we-AI hhayi indlela yokushintsha iseluleko somuntu osemthethweni sezempilo.",
    placeholder: "Chaza izimpawu zakho noma buza umbuzo...",
    typing: "U-VitalAi uhlaziya izimpawu zakho...",
    quickActions: "Tento Letephukele",
    symptomCheck: "Hlola Izimpawu",
    bookAppointment: "Bhuka Isikhathi",
    emergency: "Lusito lwe-SOS",
    loginRequired: "Kungena Kuyadingeka",
    loginMessage: "Sicela ungene ukuthola lesi sici",
    loginButton: "Ngena",
    logout: "Phuma",
    cancel: "Khansela",
    confirm: "Qinisekisa",
    send: "Thumela",
    next: "Landzelako",
    previous: "Edlule",
    headerTitle: "VitalAi",
    headerSubtitle: "UmSizi WezeMpilo",
    language: "Lulwimi",
    appointments: "Izikhathi",
    chatHistory: "Umlando Wengxoxo",
    profile: "Iphrofayili",
    login: "Ngena",
    chat: "Ingxoxo",
    you: "Wena",
    recommended: "Kunconywe",
    medicalEmergency: "🚨 LUSITO LWE-SOS LWEZEMPILO",
    emergencyInstructions: "Lokhu kuzwakala kubalulekile! Sicela:\n\n• Shayela u-10111 wamasevisi aphuthumayo\n• Iya esibhedlela esiseduzane ngokushesha\n• Ungabambi ithuba lokufuna usizo lobungcweti",
    callEmergency: "Shayela u-10111",
    symptomChecker: "Isihloli Sezimpawu",
    mainSymptom: "Iyiphi impawu yakho eyinhloko namuhla?",
    symptomDuration: "Ubesenazo isikhathi esingakanani lezi zimpawu?",
    symptomSeverity: "Zimbi kangakanani izinkinga zakho?",
    lessThan24: "Ngaphansi kwamahora angu-24",
    oneToThreeDays: "Izinsuku ezi-1-3",
    moreThan3Days: "Izinsuku ezingaphezu kwezi-3",
    mild: "Kuncane - ngenza imisebenzi evamile",
    moderate: "Okuphakathi nendawo - kuphazamisa imisebenzi",
    severe: "Kubi kakhulu - angikwazi ukwenza imisebenzi evamile",
    bookAppointmentTitle: "Bhuka Isikhathi",
    yourInformation: "Ulwazi Lwakho",
    fullName: "Igama Eliphelele",
    age: "Iminyaka",
    contactNumber: "Inombolo Yocingo",
    appointmentDetails: "Imininingwane Yesikhathi",
    selectDepartment: "Khetha uMnyango:",
    loadingLanguage: "Ilayisha lulwimi...",
    appointmentBooked: "✅ Isikhathi Sibhukiwe Ngempumelelo!",
    appointmentDetailsText: "📋 Imininingwane",
    patient: "Isiguli",
    department: "UMnyango",
    date: "Usuku",
    time: "Isikhathi",
    arrivalNotice: "Uzothola i-SMS yokuqinisekisa. Sicela ufike imizuzu engu-15 kusenesikhathi."
  },
  ve: {
    welcome: "👋 Ndaa! Ndi VitalAi, muendedzi wa vhutshilo ha wena. Ndi nga u thusa nga:\n\n• 🤒 U linga zwiitisi na u ita tshigwada\n• 📅 U bula tshifhinga tsha u bveledzana\n• ❓ Mafhungo othe a tshi shele mulenzhe\n• 🏥 Zwifhiofhi zwa tshigwada\n\nNdi nga u thusa hani namusi? Ndi humbela u givha uri ndi muendedzi wa AI kha u shuma hu si tshi tevhela ndaela dza sethese.",
    placeholder: "Talusa zwiitisi zwa wena kana vhudzisa mbudziso...",
    typing: "VitalAi i tea zwiitisi zwa wena...",
    quickActions: "Maitele a Vhukuma",
    symptomCheck: "Linga Zwiitisi",
    bookAppointment: "Bula Tshifhinga",
    emergency: "Tshifhinga tsha Khakhathi",
    loginRequired: "U Nwelwa U Tea",
    loginMessage: "Ndi humbela u nwela u wana tshine tsha u shuma",
    loginButton: "Nwela",
    logout: "Bva",
    cancel: "Kanedza",
    confirm: "Tendedza",
    send: "Rumela",
    next: "U Tevhelaho",
    previous: "U Fhioho",
    headerTitle: "VitalAi",
    headerSubtitle: "Muendedzi wa Vhutshilo",
    language: "Luambo",
    appointments: "Zwifhinga",
    chatHistory: "History ya Ngona",
    profile: "Profile",
    login: "Nwela",
    chat: "Ngona",
    you: "Iwe",
    recommended: "Zwo Tendelwa",
    medicalEmergency: "🚨 TSHIFHINGA TSHIA KHAAKHATHI TSHIA VHUTSHILO",
    emergencyInstructions: "Zwi tevhela zwa vhutshilo! Ndi humbela:\n\n• Lavhelesa 10111 kha tshinelele tsha khakhathi\n• Yea kha shele mulenzhe wo lavhelelwaho nga vhukuma\n• U songo edela u lava thuso ya sethese",
    callEmergency: "Lavhelesa 10111",
    symptomChecker: "Mulingi wa Zwiitisi",
    mainSymptom: "Ndi zwiitisi zwithu zwa vhukuma namusi?",
    symptomDuration: "Vhukuma vhu na tshifhinga tshifhio zwiitisi izwi?",
    symptomSeverity: "Zwiitisi zwo vhonala hani?",
    lessThan24: "Fhasi ha awara dza 24",
    oneToThreeDays: "Matshili a 1-3",
    moreThan3Days: "Matshili o fhiraho a 3",
    mild: "Vhukuma - nga ita zwine zwa vha zwi tshi itea",
    moderate: "Vhukati - zwi khakhatha zwine zwa vha zwi tshi itea",
    severe: "Khakhathi - a thi koni u ita zwine zwa vha zwi tshi itea",
    bookAppointmentTitle: "Bula Tshifhinga",
    yourInformation: "Mafhungo A Wena",
    fullName: "Dzina Loothe",
    age: "Maranga",
    contactNumber: "Nomoro ya Vhudzisani",
    appointmentDetails: "Mafhungo a Tshifhinga",
    selectDepartment: "Nanga Tshigwada:",
    loadingLanguage: "Layisha luambo...",
    appointmentBooked: "✅ Tshifhinga Tshi Bulwa nga Mafhungo!",
    appointmentDetailsText: "📋 Mafhungo",
    patient: "Muvhangi",
    department: "Tshigwada",
    date: "Duvha",
    time: "Tshifhinga",
    arrivalNotice: "Iwe u do wana SMS ya u tendela. Ndi humbela u swika mitshini i 15 phanḓa."
  },
  nr: {
    welcome: "👋 Lotjhani! Ngingu-VitalAi, umsizi wakho wezempilo. Ngingakusiza nge:\n\n• 🤒 Ukuhlola izimpawu kanye nokuhlela\n• 📅 Ukubhuka izikhathi zokuhlangana\n• ❓ Ulwazi lwesibhedlela jikelele\n• 🏥 Izinkomba zomnyango\n\nNgingakusiza njani namuhla? Ngicela ukhumbule ukuthi ngingumsizi we-AI hhayi indlela yokushintsha iseluleko somuntu osemthethweni sezempilo.",
    placeholder: "Chaza izimpawu zakho noma buza umbuzo...",
    typing: "U-VitalAi uhlaziya izimpawu zakho...",
    quickActions: "Izenzo Ezisheshayo",
    symptomCheck: "Hlola Izimpawu",
    bookAppointment: "Bhuka Isikhathi",
    emergency: "Ingxaki ephuthumayo",
    loginRequired: "Ukungena Kuyadingeka",
    loginMessage: "Sicela ungene ukuthola lesi sici",
    loginButton: "Ngena",
    logout: "Phuma",
    cancel: "Khansela",
    confirm: "Qinisekisa",
    send: "Thumela",
    next: "Olandelayo",
    previous: "Edlule",
    headerTitle: "VitalAi",
    headerSubtitle: "UmSizi WezeMpilo",
    language: "Ulimi",
    appointments: "Izikhathi",
    chatHistory: "Umlando Wengxoxo",
    profile: "Iphrofayili",
    login: "Ngena",
    chat: "Ingxoxo",
    you: "Wena",
    recommended: "Kunconywe",
    medicalEmergency: "🚨 INGXAKI EPHUTHUMAYO YEZEMPILO",
    emergencyInstructions: "Lokhu kuzwakala kubalulekile! Sicela:\n\n• Shayela u-10111 wamasevisi aphuthumayo\n• Iya esibhedlela esiseduzane ngokushesha\n• Ungabambi ithuba lokufuna usizo lobungcweti",
    callEmergency: "Shayela u-10111",
    symptomChecker: "Isihloli Sezimpawu",
    mainSymptom: "Iyiphi impawu yakho eyinhloko namuhla?",
    symptomDuration: "Ubesenazo isikhathi esingakanani lezi zimpawu?",
    symptomSeverity: "Zimbi kangakanani izinkinga zakho?",
    lessThan24: "Ngaphansi kwamahora angu-24",
    oneToThreeDays: "Izinsuku ezi-1-3",
    moreThan3Days: "Izinsuku ezingaphezu kwezi-3",
    mild: "Kuncane - ngenza imisebenzi evamile",
    moderate: "Okuphakathi nendawo - kuphazamisa imisebenzi",
    severe: "Kubi kakhulu - angikwazi ukwenza imisebenzi evamile",
    bookAppointmentTitle: "Bhuka Isikhathi",
    yourInformation: "Ulwazi Lwakho",
    fullName: "Igama Eliphelele",
    age: "Iminyaka",
    contactNumber: "Inombolo Yocingo",
    appointmentDetails: "Imininingwane Yesikhathi",
    selectDepartment: "Khetha uMnyango:",
    loadingLanguage: "Ilayisha ulimi...",
    appointmentBooked: "✅ Isikhathi Sibhukiwe Ngempumelelo!",
    appointmentDetailsText: "📋 Imininingwane",
    patient: "Isiguli",
    department: "UMnyango",
    date: "Usuku",
    time: "Isikhathi",
    arrivalNotice: "Uzothola i-SMS yokuqinisekisa. Sicela ufike imizuzu engu-15 kusenesikhathi."
  }
};

// Translation service class
class TranslationService {
  constructor() {
    this.language = 'en';
    this.translations = preTranslatedContent;
  }

  // Set active language for UI
  setLanguage(lang) {
    if (RSA_LANGUAGES.includes(lang)) {
      this.language = lang;
    }
  }

  // Get UI text (offline dictionary)
  t(key) {
    const lang = this.language;
    return (this.translations[lang] && this.translations[lang][key]) || 
           (this.translations['en'] && this.translations['en'][key]) || 
           key;
  }

  // Get all content for a language
  getContent(lang = this.language) {
    return this.translations[lang] || this.translations['en'];
  }

  // Get current language
  getCurrentLanguage() {
    return this.language;
  }

  // Get language name
  getLanguageName(code) {
    const languageNames = {
      en: 'English',
      af: 'Afrikaans',
      zu: 'isiZulu',
      xh: 'isiXhosa',
      nso: 'Sesotho sa Leboa',
      st: 'Sesotho',
      tn: 'Setswana',
      ts: 'Xitsonga',
      ss: 'siSwati',
      ve: 'Tshivenda',
      nr: 'isiNdebele'
    };
    return languageNames[code] || 'English';
  }
}

// Singleton instance
export const translationService = new TranslationService();

// React hook for components
export const useTranslator = () => {
  const [language, setLanguage] = useState('en');
  const [isTranslating, setIsTranslating] = useState(false);

  useEffect(() => {
    translationService.setLanguage(language);
  }, [language]);

  const t = (key) => translationService.t(key);
  
  const getContent = () => translationService.getContent();
  
  const changeLanguage = (lang) => {
    if (RSA_LANGUAGES.includes(lang)) {
      setIsTranslating(true);
      setLanguage(lang);
      // Simulate translation loading
      setTimeout(() => setIsTranslating(false), 500);
    }
  };

  const getCurrentLanguage = () => translationService.getCurrentLanguage();
  
  const getLanguageName = (code) => translationService.getLanguageName(code);

  return {
    t,
    language,
    changeLanguage,
    getContent,
    getCurrentLanguage,
    getLanguageName,
    isTranslating
  };
};

export default TranslationService;